### ISSUE TITLE
Configuration Issues with TypeScript: Suggested `tsconfig.json` Enhancements

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#26]
I've encountered several TypeScript configuration issues while setting up the project. Specifically, I ran into problems with JSX recognition, module resolution using path aliases, and importing modules like React. Here are the error messages I encountered:

1. "Cannot use JSX unless the '--jsx' flag is provided.ts(17004)"
2. "Cannot find module '@/app/SignedInProvider' or its corresponding type declarations.ts(2307)"
3. "Module '"/Users/[username]/tools/git/react-native-omh-auth/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flagts(1259)"

To resolve these issues, I adjusted the `tsconfig.json` as follows:

```json
{
  "compilerOptions": {
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "esModuleInterop": true
  }
}
```

This configuration resolved the problems I was facing. I wanted to check with you if perhaps the `tsconfig.json` is missing from the repository, or if there might be other settings or steps I am missing for setup.

Could you please confirm if this configuration aligns with the project's intended setup, or provide any additional guidance or corrections?

Thank you!

**Comment by dzuluaga** [comment]
@Nataliagros has this been addressed? Thanks

**Comment by adamTrz** [comment]
Hi @dzuluaga could you please check again if issue is still there? As far as I know everyone from our team don't encounter this TS issues in their editors, maybe your VSCode config is somehow broken?

**Comment by dzuluaga** [comment]
It's working fine now 🤷🏻‍♂️. Thanks, for looking into it.
