### ISSUE TITLE
Add Animations for OMH Auth React Native Sample App in README.md and Getting Started docs

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#62]
We would like to request the addition of animations (animated GIFs) for the OMH Auth React Native sample app, similar to those provided for the OMH Auth Android Native app.

### Reference

Please refer to the animated GIFs provided in the OMH Auth Android Native repository: [OMH Auth Android Native Animations](https://github.com/openmobilehub/android-omh-maps?tab=readme-ov-file#a-single-codebase-running-seamlessly-on-any-device).

### Best Practices

The same best practices applied to the Android repositories should be followed for the React Native repositories to ensure consistency and clarity.

### Justification

Adding these animations will greatly enhance the usability and comprehension of the sample app, providing developers with a clearer understanding of its functionality.

Thank you for your attention to this request.

**Comment by dzuluaga** [comment]
@Nataliagros friendly ping. These animation help visualize the SDKs at a glance and are important for the release and UAT. Thanks.

**Comment by Nataliagros** [comment]
Hi @dzuluaga we added this request to our current sprint; Animations will be delivered soon.

**Comment by dzuluaga** [comment]
Thanks, Natalia.
