### ISSUE TITLE
Clarify Providers Setup in Documentation

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#67]
The documentation for setting up provider secrets needs clarification regarding which files are for Android and which are for iOS. We shouldn't assume developers are familiar with Android or iOS, as many may come from desktop and web backgrounds.

**Proposed Changes:**

Update the setup steps to include these notes:

```bash
# In apps/sample-app/android
# Note: The local.properties file is for the Android setup.
cp local.properties.sample local.properties
```

```bash
# In apps/sample-app
# Note: The .env file is for the iOS setup.
cp .env.sample .env
```

CC - @artus9033 in case it similarly applies to Maps. Thanks!

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This has been addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-auth/pull/70/commits/b08882e32025c132ed5b6f91a84917ed60d86861.

**Comment by dzuluaga** [comment]
Thanks. LGTM
