### ISSUE TITLE
Providers Setup Section

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#68]
Please update the `contribution.md` guide to include a reminder for developers to follow the steps for creating an app for each service provider before proceeding with the setup. This update should reference the detailed instructions available in the Provider Configuration section.

#### Proposed Change

Add the following reminder to the `Providers Setup` section:

---

### Providers Setup

Before proceeding with the setup, please ensure you have created an app for each service provider. Detailed instructions can be found in the [Provider Configuration section](https://www.openmobilehub.com/react-native-omh-auth/docs/getting-started#provider-configuration).

Create files from templates that contain secrets for specific providers. If you don't want to set up certain providers, you can leave their values empty.

```bash
# In apps/sample-app/android
cp local.properties.sample local.properties
```

```bash
# In apps/sample-app
cp .env.sample .env
```

---

#### Rationale

This reminder will help developers avoid setup issues by ensuring they complete the necessary steps for provider configuration. It will make the setup process smoother and more efficient.

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This has been addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-auth/pull/70/commits/04a42c530620a9674eaa4b13dfc351ebbbdb67ca.

**Comment by dzuluaga** [comment]
LGTM. Thanks.
