### ISSUE TITLE
Auth token is not displayed in the dark mode

### ISSUE THREAD

**Issue by itsme291** [openmobilehub/react-native-omh-auth#71]
Auth token is not displayed when my phone is in dark mode. Tested on Huawei HMS phone 
<img width="388" alt="image" src="https://github.com/openmobilehub/react-native-omh-auth/assets/42480508/ba5e86d9-d74f-4f24-ab63-6c192b69a518">

**Comment by dzuluaga** [comment]
@Nataliagros PTAL. Thanks!

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This was addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-auth/commit/2477e9832757d0ba02a61d09f3c259fcfef5a34d.
