### ISSUE TITLE
Distribute Sample App to App Center & Build Docs job fails in RN OMH Auth

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#75]
The Distribute Sample App to App Center & Build Docs job fails for the `react-native-omh-auth` repository. I had to manually update the workflow, and the issue seems to be fixed. However, I am not sure if changing `turbo.json` has any side effects.

**Link to failed run**: [GitHub Actions run #9471566281](https://github.com/openmobilehub/react-native-omh-auth/actions/runs/9471566281)

**Steps taken**:
- Manually updated the workflow
- The issue appears to be resolved after this change

**Request**:
Please confirm if the changes made to `turbo.json` have any side effects or if any further action is needed.

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This was addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-auth/pull/79/commits/6f95ed4df044465265e2d6da18b8c9f62545005e.
