### ISSUE TITLE
[BLOCKING ISSUE] Missing Module for Dependency in `openmobilehub_auth-google` and other plugins

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#85]
Hey folks,

I'm encountering a blocking issue while trying to build the `reactNativeOmhAuthFromScratch` project. Specifically, the build is failing due to a missing module dependency in the `openmobilehub_auth-google` package. The error message points to the following line in the `build.gradle` file:

```
A problem occurred evaluating project ':openmobilehub_auth-google'.
> Project with path ':omh-auth-core' could not be found in project ':openmobilehub_auth-google'.
```

This issue indicates that the `omh-auth-core` module is missing, which is causing the build to fail. The module appears to be required by the `openmobilehub_auth-google` package but is not included or referenced correctly in the project.

#### Steps to Reproduce
1. Clone the `reactNativeOmhAuthFromScratch` project.
2. Set up the development environment as per the instructions.
3. Run the command `npx react-native run-android`.
4. Observe the build failure due to the missing `omh-auth-core` module.

#### Expected Behavior
The build process should complete successfully, with all dependencies resolved correctly.

#### Observed Behavior
The build fails with the error mentioned above, indicating that the `omh-auth-core` module is missing.

#### Additional Context
This dependency issue is concerning because it suggests that the `openmobilehub_auth-google` module might have been tested outside of the sample app, relying on local modules that are not properly referenced in the project. This raises a flag as the module is currently unusable in its present state.

Additionally, other modules such as `plugin-facebook`, `plugin-microsoft`, and `plugin-dropbox` might have similar issues. These dependencies should be reviewed to ensure they are correctly referenced and usable within the project.

#### Impact
This is a blocking issue preventing further development and testing of the `reactNativeOmhAuthFromScratch` project. Resolving this is critical to ensure the module can be used as intended.

#### Priority Request
Please prioritize this issue over other features as this module has already been delivered and released to the developer community. Ensuring that the module is functional is essential to maintain the integrity and usability of the project.

#### Request
Please review the `openmobilehub_auth-google` module and its dependencies, particularly the `omh-auth-core` module. Also, consider checking other related modules (`plugin-facebook`, `plugin-microsoft`, `plugin-dropbox`) to ensure they don't have similar issues as I notice the `build.gradle` is also referencing the same `:omh-auth-core` module.

Thank you for your attention to this matter.

**Comment by andrei-zgirvaci** [comment]
Hi @dzuluaga, thanks for bringing this to our attention! Just to make sure that the setup is correct. Have you followed the [Android configuration](https://openmobilehub.github.io/react-native-omh-auth/docs/getting-started#android-configuration)?

**Comment by dzuluaga** [comment]
Gotcha. Will try it again and get back to you. Thank you.

**Comment by dzuluaga** [comment]
Actualy both pages return 404. Could you please look into it? Please check the pages before closing the feature.

https://openmobilehub.org/react-native-omh-auth/docs/getting-started#ios-configuration
https://openmobilehub.org/react-native-omh-auth/docs/getting-started#android-configuration

**Comment by adamTrz** [comment]
Here are correct links:
https://openmobilehub.github.io/react-native-omh-auth/docs/getting-started/#ios-configuration
https://openmobilehub.github.io/react-native-omh-auth/docs/getting-started/#android-configuration

**Comment by dzuluaga** [comment]
Okay. I fixed them [here](https://github.com/openmobilehub/react-native-omh-auth/commit/2646c4f5b48e765c74e3beacd57b0a72bbcd5d31).
